### ISSUE TITLE
Not working when i set  IMAGE_HEIGHT and IMAGE_WIDTH to 250 in Network Class

### ISSUE THREAD

**Issue by Ahmad-Masood** [arahusky/Tensorflow-Segmentation#2]
Shapes (?,1,1,64) and (?,2,2,64) not compatible

**Comment by Ahmad-Masood** [comment]
I think it would work fine if our images would be of size 256

**Comment by arahusky** [comment]
Current architecture contains three shrinking convolutions and three max pools each reducing original image size by 2. The middle layer (the layer after last max pooling -- named max_3) thus contains image with dimensions [1, original_height / 2^6, original_width / 2^6, 64]. Therefore, you should either make your input image dimensions multiples of 2^6 = 64 (recommended), or redefine network architecture.

Your second comment is thus correct. Image with shape [256, 256] should work.
