### ISSUE TITLE
Shape Problem

### ISSUE THREAD

**Issue by Fab1900** [arahusky/Tensorflow-Segmentation#3]
Hey,
I try to run your code with my own dataset (3250x1526 images) but when the Optimizer should start, I get this error:
  raise ValueError("Shapes %s and %s are not compatible" % (self, other))
ValueError: Shapes (?, 1625, 763, 64) and (?, 1626, 764, 64) are not compatible

Do you have any idea what the issue is ?

**Comment by arahusky** [comment]
Hello Fab,
see #2 for answer to your problem. Basically, the image dimensions should be multiples of 64 for current network architecture.

**Comment by Fab1900** [comment]
Thank you! What is the reason for that?
